In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/g-research-crypto-forecasting/example_sample_submission.csv
/kaggle/input/g-research-crypto-forecasting/asset_details.csv
/kaggle/input/g-research-crypto-forecasting/example_test.csv
/kaggle/input/g-research-crypto-forecasting/train.csv
/kaggle/input/g-research-crypto-forecasting/supplemental_train.csv
/kaggle/input/g-research-crypto-forecasting/gresearch_crypto/competition.cpython-37m-x86_64-linux-gnu.so
/kaggle/input/g-research-crypto-forecasting/gresearch_crypto/__init__.py


In [2]:
import pandas as pd
col_list = ['timestamp', 'Asset_ID','Close','Target']
df_t = pd.read_csv('../input/g-research-crypto-forecasting/train.csv', low_memory=False, 
                       dtype={'Asset_ID': 'int8', 'Count': 'int32', 'row_id': 'int32', 'Count': 'int32', 
                              'Open': 'float64', 'High': 'float64', 'Low': 'float64', 'Close': 'float64', 
                              'Volume': 'float64', 'VWAP': 'float64'
                             },usecols=col_list
                      )
df_t.head(3)


timestamp  Asset_ID      Close    Target
0  1514764860         2   2374.590 -0.004218
1  1514764860         0      8.530 -0.014399
2  1514764860         1  13850.176 -0.014643

In [3]:
df_t.tail(10)

timestamp  Asset_ID        Close  Target
24236796  1632182400         4     0.208294     NaN
24236797  1632182400         5     4.195740     NaN
24236798  1632182400         7    49.068150     NaN
24236799  1632182400         6  2972.603333     NaN
24236800  1632182400         8     1.282550     NaN
24236801  1632182400         9   156.943857     NaN
24236802  1632182400        10  2432.907467     NaN
24236803  1632182400        13     0.091349     NaN
24236804  1632182400        12     0.282051     NaN
24236805  1632182400        11   232.275000     NaN

In [4]:
#df_reduce=reduce_mem_usage(df_t)
df_reduce=df_t
df_reduce

timestamp  Asset_ID         Close    Target
0         1514764860         2   2374.590000 -0.004218
1         1514764860         0      8.530000 -0.014399
2         1514764860         1  13850.176000 -0.014643
3         1514764860         5      7.657600 -0.013922
4         1514764860         7     25.877000 -0.008264
...              ...       ...           ...       ...
24236801  1632182400         9    156.943857       NaN
24236802  1632182400        10   2432.907467       NaN
24236803  1632182400        13      0.091349       NaN
24236804  1632182400        12      0.282051       NaN
24236805  1632182400        11    232.275000       NaN

[24236806 rows x 4 columns]

In [5]:
df_reduce.shape

(24236806, 4)

In [6]:
df=df_reduce#.head(24236)
df.shape

(24236806, 4)

In [7]:
df.head()

timestamp  Asset_ID       Close    Target
0  1514764860         2   2374.5900 -0.004218
1  1514764860         0      8.5300 -0.014399
2  1514764860         1  13850.1760 -0.014643
3  1514764860         5      7.6576 -0.013922
4  1514764860         7     25.8770 -0.008264

In [8]:
df.tail()

timestamp  Asset_ID        Close  Target
24236801  1632182400         9   156.943857     NaN
24236802  1632182400        10  2432.907467     NaN
24236803  1632182400        13     0.091349     NaN
24236804  1632182400        12     0.282051     NaN
24236805  1632182400        11   232.275000     NaN

In [9]:
df.isnull().sum()

timestamp         0
Asset_ID          0
Close             0
Target       750338
dtype: int64

In [10]:
df.dropna(subset = ["Target"], inplace=True)

In [11]:
#df.dropna(subset = ["VWAP"], inplace=True)

In [12]:
#df.dropna(subset = ["Target"], inplace=True)

In [13]:
df.isnull().sum()

timestamp    0
Asset_ID     0
Close        0
Target       0
dtype: int64

In [14]:
#df1=df.reset_index()[['Close','timestamp']]
df1=df#[['timestamp','Close','VWAP','Asset_ID','Target']]
df1.head()

timestamp  Asset_ID       Close    Target
0  1514764860         2   2374.5900 -0.004218
1  1514764860         0      8.5300 -0.014399
2  1514764860         1  13850.1760 -0.014643
3  1514764860         5      7.6576 -0.013922
4  1514764860         7     25.8770 -0.008264

In [15]:
col_list = ['timestamp', 'Asset_ID','Close','row_id','group_num']
testdf=pd.read_csv('../input/g-research-crypto-forecasting/example_test.csv', low_memory=False, 
                       dtype={'Asset_ID': 'int8', 'Count': 'int32', 'row_id': 'int32', 'Count': 'int32', 
                              'Open': 'float64', 'High': 'float64', 'Low': 'float64', 'Close': 'float64', 
                              'Volume': 'float64', 'VWAP': 'float64','group_num': 'int8'
                             },usecols=col_list
                      )
testdf.head()

timestamp  Asset_ID         Close  group_num  row_id
0  1623542400         3      1.483681          0       0
1  1623542400         2    582.276667          0       1
2  1623542400         0    344.598000          0       2
3  1623542400         1  35602.004286          0       3
4  1623542400         4      0.312208          0       4

In [16]:
testdf.head

<bound method NDFrame.head of      timestamp  Asset_ID         Close  group_num  row_id
0   1623542400         3      1.483681          0       0
1   1623542400         2    582.276667          0       1
2   1623542400         0    344.598000          0       2
3   1623542400         1  35602.004286          0       3
4   1623542400         4      0.312208          0       4
5   1623542400         5      4.837583          0       5
6   1623542400         7     55.344680          0       6
7   1623542400         6   2374.380714          0       7
8   1623542400         8      1.003300          0       8
9   1623542400         9    162.214714          0       9
10  1623542400        10   2947.078025          0      10
11  1623542400        13      0.068158          0      11
12  1623542400        12      0.328829          0      12
13  1623542400        11    243.532500          0      13
14  1623542460         3      1.482043          1      14
15  1623542460         2    582.358333    

In [17]:
df1.head(2)

timestamp  Asset_ID    Close    Target
0  1514764860         2  2374.59 -0.004218
1  1514764860         0     8.53 -0.014399

In [18]:
train=df1.iloc[:15266204]

In [19]:
test=df1.iloc[15266204:]

In [20]:
X_train1=train.iloc[:, :3]
y_train=train.iloc[:, -1:]

In [21]:
X_test1=test.iloc[:, :3]
y_test=test.iloc[:, -1:]

In [22]:
#np.isnan(df1.any()) #and gets False


In [23]:
#np.isfinite(df1.all()) #and gets True

In [24]:
#df1[np.isfinite(df1) == True] = 0

In [25]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler(feature_range=(0,1))
X_train=scaler.fit_transform(np.array(X_train1))
X_test=scaler.fit_transform(np.array(X_test1))



In [26]:
X_train

array([[0.00000000e+00, 1.53846154e-01, 1.38225186e-01],
       [0.00000000e+00, 0.00000000e+00, 4.96464442e-04],
       [0.00000000e+00, 7.69230769e-02, 8.06220836e-01],
       ...,
       [9.99999266e-01, 8.46153846e-01, 5.06334222e-03],
       [1.00000000e+00, 2.30769231e-01, 8.42871997e-06],
       [1.00000000e+00, 1.53846154e-01, 1.68800039e-02]])

In [27]:
y_train

Target
0        -0.004218
1        -0.014399
2        -0.014643
3        -0.013922
4        -0.008264
...            ...
15962365  0.002686
15962366  0.005847
15962367 -0.000875
15962368 -0.001392
15962369 -0.003463

[15266204 rows x 1 columns]

In [28]:
df1.shape

(23486468, 4)

In [29]:
"""##splitting dataset into train and test split
training_size=int(len(df1)*0.65)
test_size=len(df1)-training_size
train_data,test_data=df1[0:training_size,:],df1[training_size:len(df1),:]"""

'##splitting dataset into train and test split\ntraining_size=int(len(df1)*0.65)\ntest_size=len(df1)-training_size\ntrain_data,test_data=df1[0:training_size,:],df1[training_size:len(df1),:]'

In [30]:
"""training_size,test_size"""

'training_size,test_size'

In [31]:
#train_data

In [32]:
#test_data

In [33]:
#X_train ,y_train =train_data[:, [0,1,2]], train_data[:, [3]]
#y_train = train_data[4] 
#X_test, ytest = test_data[:, [0,1,2]], test_data[:, [3]]


In [34]:
print('X_train.shape',X_train.shape)
print('y_train.shape',y_train.shape)

X_train.shape (15266204, 3)
y_train.shape (15266204, 1)


In [35]:
#print(test_data.shape)

In [36]:
print(X_test.shape), print(y_test.shape)

(8220264, 3)
(8220264, 1)


(None, None)

In [37]:
# reshape input to be [samples, time steps, features] which is required for LSTM
X_train =X_train.reshape(X_train.shape[0],X_train.shape[1] , 1)
X_test = X_test.reshape(X_test.shape[0],X_test.shape[1] , 1)

In [38]:
### Create the Stacked LSTM model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM

In [39]:
model=Sequential()
model.add(LSTM(50,return_sequences=True,input_shape=(3,1)))
model.add(LSTM(50,return_sequences=True))
model.add(LSTM(50))
model.add(Dense(1))
model.compile(loss='mean_squared_error',optimizer='adam')


User settings:

   KMP_AFFINITY=granularity=fine,verbose,compact,1,0
   KMP_BLOCKTIME=0
   KMP_DUPLICATE_LIB_OK=True
   KMP_INIT_AT_FORK=FALSE
   KMP_SETTINGS=1
   KMP_WARNINGS=0

Effective settings:

   KMP_ABORT_DELAY=0
   KMP_ADAPTIVE_LOCK_PROPS='1,1024'
   KMP_ALIGN_ALLOC=64
   KMP_ALL_THREADPRIVATE=128
   KMP_ATOMIC_MODE=2
   KMP_BLOCKTIME=0
   KMP_CPUINFO_FILE: value is not defined
   KMP_DETERMINISTIC_REDUCTION=false
   KMP_DEVICE_THREAD_LIMIT=2147483647
   KMP_DISP_NUM_BUFFERS=7
   KMP_DUPLICATE_LIB_OK=true
   KMP_ENABLE_TASK_THROTTLING=true
   KMP_FORCE_REDUCTION: value is not defined
   KMP_FOREIGN_THREADS_THREADPRIVATE=true
   KMP_FORKJOIN_BARRIER='2,2'
   KMP_FORKJOIN_BARRIER_PATTERN='hyper,hyper'
   KMP_GTID_MODE=3
   KMP_HANDLE_SIGNALS=false
   KMP_HOT_TEAMS_MAX_LEVEL=1
   KMP_HOT_TEAMS_MODE=0
   KMP_INIT_AT_FORK=true
   KMP_LIBRARY=throughput
   KMP_LOCK_KIND=queuing
   KMP_MALLOC_POOL_INCR=1M
   KMP_NUM_LOCKS_IN_BLOCK=1
   KMP_PLAIN_BARRIER='2,2'
   KMP_PLAIN_BARRIER_P

In [40]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm (LSTM)                  (None, 3, 50)             10400     
_________________________________________________________________
lstm_1 (LSTM)                (None, 3, 50)             20200     
_________________________________________________________________
lstm_2 (LSTM)                (None, 50)                20200     
_________________________________________________________________
dense (Dense)                (None, 1)                 51        
Total params: 50,851
Trainable params: 50,851
Non-trainable params: 0
_________________________________________________________________


In [41]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm (LSTM)                  (None, 3, 50)             10400     
_________________________________________________________________
lstm_1 (LSTM)                (None, 3, 50)             20200     
_________________________________________________________________
lstm_2 (LSTM)                (None, 50)                20200     
_________________________________________________________________
dense (Dense)                (None, 1)                 51        
Total params: 50,851
Trainable params: 50,851
Non-trainable params: 0
_________________________________________________________________


In [42]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=1,batch_size=64,verbose=1)

2022-01-30 14:01:05.112280: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)


238535/238535 [==============================] - 3848s 16ms/step - loss: 2.9829e-05 - val_loss: 3.7313e-05


In [43]:
import tensorflow as tf
tf.__version__

'2.6.2'

In [44]:
### Lets Do the prediction and check performance metrics
#train_predict=model.predict(X_train)
#test_predict=model.predict(X_test)

In [45]:
#print('train_predict.shape',train_predict.shape)
#print('test_predict.shape',test_predict.shape)

In [46]:
print('X_train.shape',X_train.shape)
print('y_train.shape',y_train.shape)
print('X_test.shape',X_test.shape)
print('ytest.shape',y_test.shape)

X_train.shape (15266204, 3, 1)
y_train.shape (15266204, 1)
X_test.shape (8220264, 3, 1)
ytest.shape (8220264, 1)


In [47]:
### Calculate RMSE performance metrics
#import math
#from sklearn.metrics import mean_squared_error
#math.sqrt(mean_squared_error(y_train,train_predict))

In [48]:
### Test Data RMSE
#math.sqrt(mean_squared_error(ytest,test_predict))

In [49]:
test1=testdf[['timestamp', 'Asset_ID','Close']]

In [50]:
test1.head()

timestamp  Asset_ID         Close
0  1623542400         3      1.483681
1  1623542400         2    582.276667
2  1623542400         0    344.598000
3  1623542400         1  35602.004286
4  1623542400         4      0.312208

In [51]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler(feature_range=(0,1))
test3=scaler.fit_transform(np.array(test1))

In [52]:
test3.shape


(56, 3)

In [53]:
test3

array([[0.00000000e+00, 2.30769231e-01, 3.97659644e-05],
       [0.00000000e+00, 1.53846154e-01, 1.63532883e-02],
       [0.00000000e+00, 0.00000000e+00, 9.67728442e-03],
       [0.00000000e+00, 7.69230769e-02, 1.00000000e+00],
       [0.00000000e+00, 3.07692308e-01, 6.86121108e-06],
       [0.00000000e+00, 3.84615385e-01, 1.33971571e-04],
       [0.00000000e+00, 5.38461538e-01, 1.55263308e-03],
       [0.00000000e+00, 4.61538462e-01, 6.66905517e-02],
       [0.00000000e+00, 6.15384615e-01, 2.62728406e-05],
       [0.00000000e+00, 6.92307692e-01, 4.55443706e-03],
       [0.00000000e+00, 7.69230769e-01, 8.27766799e-02],
       [0.00000000e+00, 1.00000000e+00, 6.23561589e-09],
       [0.00000000e+00, 9.23076923e-01, 7.32804711e-06],
       [0.00000000e+00, 8.46153846e-01, 6.83852029e-03],
       [3.33333334e-01, 2.30769231e-01, 3.97199519e-05],
       [3.33333334e-01, 1.53846154e-01, 1.63555822e-02],
       [3.33333334e-01, 0.00000000e+00, 9.66300149e-03],
       [3.33333334e-01, 7.69230

In [54]:
test4 =test3.reshape(test3.shape[0],test3.shape[1] , 1)

In [55]:
test4

array([[[0.00000000e+00],
        [2.30769231e-01],
        [3.97659644e-05]],

       [[0.00000000e+00],
        [1.53846154e-01],
        [1.63532883e-02]],

       [[0.00000000e+00],
        [0.00000000e+00],
        [9.67728442e-03]],

       [[0.00000000e+00],
        [7.69230769e-02],
        [1.00000000e+00]],

       [[0.00000000e+00],
        [3.07692308e-01],
        [6.86121108e-06]],

       [[0.00000000e+00],
        [3.84615385e-01],
        [1.33971571e-04]],

       [[0.00000000e+00],
        [5.38461538e-01],
        [1.55263308e-03]],

       [[0.00000000e+00],
        [4.61538462e-01],
        [6.66905517e-02]],

       [[0.00000000e+00],
        [6.15384615e-01],
        [2.62728406e-05]],

       [[0.00000000e+00],
        [6.92307692e-01],
        [4.55443706e-03]],

       [[0.00000000e+00],
        [7.69230769e-01],
        [8.27766799e-02]],

       [[0.00000000e+00],
        [1.00000000e+00],
        [6.23561589e-09]],

       [[0.00000000e+00],
        [9.230

In [56]:
predict=model.predict(test4)

In [57]:
testNew=pd.read_csv('../input/g-research-crypto-forecasting/example_test.csv')
testNew.head(3)

timestamp  Asset_ID   Count        Open       High      Low       Close  \
0  1623542400         3  1201.0    1.478556    1.48603    1.478    1.483681   
1  1623542400         2  1020.0  580.306667  583.89000  579.910  582.276667   
2  1623542400         0   626.0  343.789500  345.10800  343.640  344.598000   

          Volume        VWAP  group_num  row_id  
0  654799.561103    1.481439          0       0  
1    1227.988328  581.697038          0       1  
2    1718.832569  344.441729          0       2

In [58]:
predict.shape

(56, 1)

In [59]:
predict

array([[0.00021334],
       [0.00021336],
       [0.00021341],
       [0.00021324],
       [0.00021332],
       [0.0002133 ],
       [0.00021325],
       [0.00021326],
       [0.00021323],
       [0.00021321],
       [0.00021318],
       [0.00021313],
       [0.00021315],
       [0.00021317],
       [0.00021321],
       [0.00021323],
       [0.00021328],
       [0.00021311],
       [0.00021319],
       [0.00021317],
       [0.00021312],
       [0.00021313],
       [0.0002131 ],
       [0.00021308],
       [0.00021305],
       [0.000213  ],
       [0.00021302],
       [0.00021304],
       [0.00021309],
       [0.00021311],
       [0.00021316],
       [0.00021299],
       [0.00021307],
       [0.00021305],
       [0.000213  ],
       [0.00021301],
       [0.00021298],
       [0.00021296],
       [0.00021293],
       [0.00021288],
       [0.0002129 ],
       [0.00021292],
       [0.00021298],
       [0.000213  ],
       [0.00021305],
       [0.00021289],
       [0.00021296],
       [0.000

In [60]:
print("No. of dimensions: ", predict.ndim)

No. of dimensions:  2


In [61]:
predict1=predict.flatten()

In [62]:
predict1

array([0.00021334, 0.00021336, 0.00021341, 0.00021324, 0.00021332,
       0.0002133 , 0.00021325, 0.00021326, 0.00021323, 0.00021321,
       0.00021318, 0.00021313, 0.00021315, 0.00021317, 0.00021321,
       0.00021323, 0.00021328, 0.00021311, 0.00021319, 0.00021317,
       0.00021312, 0.00021313, 0.0002131 , 0.00021308, 0.00021305,
       0.000213  , 0.00021302, 0.00021304, 0.00021309, 0.00021311,
       0.00021316, 0.00021299, 0.00021307, 0.00021305, 0.000213  ,
       0.00021301, 0.00021298, 0.00021296, 0.00021293, 0.00021288,
       0.0002129 , 0.00021292, 0.00021298, 0.000213  , 0.00021305,
       0.00021289, 0.00021296, 0.00021294, 0.00021289, 0.00021291,
       0.00021287, 0.00021285, 0.00021282, 0.00021278, 0.00021279,
       0.00021281], dtype=float32)

In [63]:
testNew.shape

(56, 11)

In [64]:
#data = {'row_id':testNew.row_id,
        
       # 'Target':predict1}
#output=pd.DataFrame(data)
#data

In [65]:
#predict = model.predict(X_train)

output = pd.DataFrame({
                       'group_num':testNew.group_num,
                        'row_id': testNew.row_id,
                       'Target': predict1})
output.to_csv('submission.csv' , index=False)
print("Submission saved")

Submission saved


In [66]:
#output.to_csv('output.csv')

In [67]:
#output